apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: koji-prometheus-exporter
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: koji-prometheus-exporter
    app.kubernetes.io/part-of: koji-prometheus-exporter
  name: koji-prometheus-exporter
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: koji-prometheus-exporter
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: koji-prometheus-exporter
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/sp-guild-resilience-tenant/koji-prometheus-exporter/koji-prometheus-exporter@sha256:7eae8926da43c5cef8564f5dc2a6e52aa7960d361693fe9eeefd86b884d1229f
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
