apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: koji-prometheus-exporter
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: koji-prometheus-exporter
    app.kubernetes.io/part-of: koji-prometheus-exporter
  name: koji-prometheus-exporter
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app.kubernetes.io/instance: koji-prometheus-exporter
status:
  loadBalancer: {}
