apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: koji-prometheus-exporter
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/sp-guild-resilience-tenant/koji-prometheus-exporter/koji-prometheus-exporter@sha256:a8b024d8b3a0078384f74475109132921fbb344906a8cca9ba80aa0dfa3e752d
        name: container-image
        resources: {}
status: {}
