apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: koji-prometheus-exporter
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/sp-guild-resilience-tenant/koji-prometheus-exporter/koji-prometheus-exporter@sha256:ce8a229dfb1382deee97dcfedaeb1c55d86898247e5318a1697555886faeb0d5
        name: container-image
        resources: {}
status: {}
