apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: koji-prometheus-exporter
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: koji-prometheus-exporter
    app.kubernetes.io/part-of: koji-prometheus-exporter
  name: koji-prometheus-exporterq37b
spec:
  port:
    targetPort: 8000
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: koji-prometheus-exporter
    weight: 100
status: {}
